### PR TITLE
I havent tested yet so can someone please test for me

### PR DESCRIPTION
**Pull request by abhay7dev**
I worked on this a few weeks ago, however, do to my computer having a messed up python installation (I have python 3.6, 3.7, and 3.8 on my home computer), i have not been able to test it because i keep getting "unable to install" pip errors for the python script so if someone can git clone and test what i have (`npm start` the backend), that would be great. Thanks.

### CODE REVIEW

**Comment by roblburris** [comment]
Hmm that's weird, PyTorch should definitely be able to install on any of those versions. Could you try installing with this command and letting me know what happens? The Windows/Linux command will also install torchaudio but you can uninstall it afterwards

Windows/Linux:
```
pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
```

Mac:
```
pip3 install torch torchvision
```

**Comment by abhay7dev** [comment]
The problem is not with installing, its with folder ocnfiguration, like i have python 3.9 on path, but pip is getting jumbled up with which folder to put it in because of the 3 versions i have installed, one came from visual studio, so its in a weird place on windows, but i will try later. thanks

**Comment by roblburris** [comment]
Gotcha. I think you should try creating a virtual environment in the `./backend/src/python/` directory or install conda. Either of these make it easy for installing new packages when you have multiple python versions installed. 

Python venv: https://docs.python.org/3/library/venv.html
Conda install: https://docs.conda.io/en/latest/

Let me know if these don't work - I'd be happy to jump on a call and help you.

**Comment by abhay7dev** [comment]
Sorry for replying so late, I was successfully able to install but i keep getting errors with the python script, i am not sure if its on my end..

**Comment by roblburris** [comment]
No worries! Would it be alright if you pasted the errors you were getting and also said which script was giving you issues?

**Comment by abhay7dev** [comment]
Hey, sorry for the delay again. I have made the various changes and it works fine on windows (with node version 12) and ubuntu linux (with node version 14). Accepting files, writing files, running the python, sending the result, and finally, deleting the file after the operation, all work as expected and is fine. However, the python machine learning script takes long time to run (it is machine learning so I guess that should happen), however, every image I submit returns the following:
```json
{"label":"ERROR: unable to perform inference\r\n"}
```

This seems to be an error with the machine learning script so I am not sure how to fix it.

**Comment by roblburris** [comment]
Hmm so it seems like the error is coming from lines 46-52 in ./backend/src/python/ml.py which correspond to these lines of code:
```python
 try:
    with open("imagenet_classes.txt", "r") as f:
      categories = [s.strip() for s in f.readlines()]
    
    return categories[predicted_index]
  except:
    return 'ERROR: unable to perform inference' 
```
We're either getting an exception because our script is unable to open the file or because `predicted_index` exceeds the length of `categories`. I feel like its the former since we're calling the script from a directory above and from what I recall, Python is weird about relative imports so it thinks the `imagenet_classes.txt` file is in the `./backend/src` directory when its really in `./backend/src/python/`. Can you try changing line 47 to the following and let me know if it works?
```python3
with open("./python/imagenet_classes.txt", "r") as f:
```
If that doesn't work, can you try replacing lines 46-52 with the following code and letting me know what gets printed?
```python3
  try:
    with open("./python/imagenet_classes.txt", "r") as f:
      categories = [s.strip() for s in f.readlines()]
    
    return categories[predicted_index]
  except Exception as e:
    print(f'Exception: {e}')
    return 'ERROR: unable to perform inference' 
```

I'm on MacOS right now but I can try on Windows in a few days. No worries if you aren't able to get to it, I'll add a new comment if I find a fix.

**Comment by abhay7dev** [comment]
What you provided first did not work so what i did instead was add another path in the `config.js` file which points to the txt file that is supposed to be read, then i pass that as another argument to the python script. It works :)

**Comment by abhay7dev** [comment]
Please, know I have not done error handling/testing yet but my code works fine

**Comment by abhay7dev** [comment]
we ever gonna finish this?

**Pull request closed without merging**
